services:
  - type: web
    name: receiptablity
    env: docker
    plan: free
    autoDeploy: true
    startCommand: gunicorn receiptablity.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: receiptablity.onrender.com
